name <- c('my','name',"is","HJ")
name2 <- c("my name is HJ")
scr_bigdata <- c(56,72,99,100,82)
scr_bigdata_max <- max(scr_bigdata)
scr_bigdata_mean <- mean(scr_bigdata)
scr_bigdata_min <- min(scr_bigdata)

scr_r <-c(100,79,65,88,93)
scr_r_max <- max(scr_r)
scr_r_mean <-  mean(scr_r)
scr_r_min <- min(scr_r)
